#define CSR_BASE 0x0L
#define CSR_CTRL_BASE (CSR_BASE + 0x0L)
#define CSR_CTRL_RESET_ADDR (CSR_BASE + 0x0L)
#define CSR_CTRL_RESET_SIZE 1
#define CSR_CTRL_SCRATCH_ADDR (CSR_BASE + 0x4L)
#define CSR_CTRL_SCRATCH_SIZE 1
#define CSR_CTRL_BUS_ERRORS_ADDR (CSR_BASE + 0x8L)
#define CSR_CTRL_BUS_ERRORS_SIZE 1
#define CSR_CTRL_RESET_SOC_RST_OFFSET 0
#define CSR_CTRL_RESET_SOC_RST_SIZE 1
#define CSR_CTRL_RESET_CPU_RST_OFFSET 1
#define CSR_CTRL_RESET_CPU_RST_SIZE 1
#define CSR_IDENTIFIER_MEM_BASE (CSR_BASE + 0x800L)
#define CSR_LA_BASE (CSR_BASE + 0x1000L)
#define CSR_LA_NUM_PROBES_ADDR (CSR_BASE + 0x1000L)
#define CSR_LA_NUM_PROBES_SIZE 1
#define CSR_LA_SAMPLERATE_ADDR (CSR_BASE + 0x1004L)
#define CSR_LA_SAMPLERATE_SIZE 1
#define CSR_LA_TRIGGER_ENABLE_ADDR (CSR_BASE + 0x1008L)
#define CSR_LA_TRIGGER_ENABLE_SIZE 1
#define CSR_LA_TRIGGER_DONE_ADDR (CSR_BASE + 0x100cL)
#define CSR_LA_TRIGGER_DONE_SIZE 1
#define CSR_LA_TRIGGER_MEM_WRITE_ADDR (CSR_BASE + 0x1010L)
#define CSR_LA_TRIGGER_MEM_WRITE_SIZE 1
#define CSR_LA_TRIGGER_MEM_MASK_ADDR (CSR_BASE + 0x1014L)
#define CSR_LA_TRIGGER_MEM_MASK_SIZE 1
#define CSR_LA_TRIGGER_MEM_VALUE_ADDR (CSR_BASE + 0x1018L)
#define CSR_LA_TRIGGER_MEM_VALUE_SIZE 1
#define CSR_LA_TRIGGER_MEM_FULL_ADDR (CSR_BASE + 0x101cL)
#define CSR_LA_TRIGGER_MEM_FULL_SIZE 1
#define CSR_LA_SUBSAMPLER_VALUE_ADDR (CSR_BASE + 0x1020L)
#define CSR_LA_SUBSAMPLER_VALUE_SIZE 1
#define CSR_LA_HSPI_TX_STATE_R_ADDR (CSR_BASE + 0x1024L)
#define CSR_LA_HSPI_TX_STATE_R_SIZE 1
#define CSR_LA_HSPI_TX_ENABLE_ADDR (CSR_BASE + 0x1028L)
#define CSR_LA_HSPI_TX_ENABLE_SIZE 1
#define CSR_LA_HSPI_TX_HSPI_WIDTH_R_ADDR (CSR_BASE + 0x102cL)
#define CSR_LA_HSPI_TX_HSPI_WIDTH_R_SIZE 1
#define CSR_LA_HSPI_TX_LOCKED_ADDR (CSR_BASE + 0x1030L)
#define CSR_LA_HSPI_TX_LOCKED_SIZE 1
#define CSR_LA_HSPI_TX_UNLOCK_ADDR (CSR_BASE + 0x1034L)
#define CSR_LA_HSPI_TX_UNLOCK_SIZE 1
#define CSR_LA_HSPI_TX_INTER_PACKET_DELAY_ADDR (CSR_BASE + 0x1038L)
#define CSR_LA_HSPI_TX_INTER_PACKET_DELAY_SIZE 1
#define CSR_LA_HSPI_TX_MAX_PACKET_SIZE_ADDR (CSR_BASE + 0x103cL)
#define CSR_LA_HSPI_TX_MAX_PACKET_SIZE_SIZE 1
#define CSR_LA_HSPI_TX_MAX_PACKET_NUM_R_ADDR (CSR_BASE + 0x1040L)
#define CSR_LA_HSPI_TX_MAX_PACKET_NUM_R_SIZE 1
#define CSR_TIMER0_BASE (CSR_BASE + 0x1800L)
#define CSR_TIMER0_LOAD_ADDR (CSR_BASE + 0x1800L)
#define CSR_TIMER0_LOAD_SIZE 1
#define CSR_TIMER0_RELOAD_ADDR (CSR_BASE + 0x1804L)
#define CSR_TIMER0_RELOAD_SIZE 1
#define CSR_TIMER0_EN_ADDR (CSR_BASE + 0x1808L)
#define CSR_TIMER0_EN_SIZE 1
#define CSR_TIMER0_UPDATE_VALUE_ADDR (CSR_BASE + 0x180cL)
#define CSR_TIMER0_UPDATE_VALUE_SIZE 1
#define CSR_TIMER0_VALUE_ADDR (CSR_BASE + 0x1810L)
#define CSR_TIMER0_VALUE_SIZE 1
#define CSR_TIMER0_EV_STATUS_ADDR (CSR_BASE + 0x1814L)
#define CSR_TIMER0_EV_STATUS_SIZE 1
#define CSR_TIMER0_EV_PENDING_ADDR (CSR_BASE + 0x1818L)
#define CSR_TIMER0_EV_PENDING_SIZE 1
#define CSR_TIMER0_EV_ENABLE_ADDR (CSR_BASE + 0x181cL)
#define CSR_TIMER0_EV_ENABLE_SIZE 1
#define CSR_TIMER0_EV_STATUS_ZERO_OFFSET 0
#define CSR_TIMER0_EV_STATUS_ZERO_SIZE 1
#define CSR_TIMER0_EV_PENDING_ZERO_OFFSET 0
#define CSR_TIMER0_EV_PENDING_ZERO_SIZE 1
#define CSR_TIMER0_EV_ENABLE_ZERO_OFFSET 0
#define CSR_TIMER0_EV_ENABLE_ZERO_SIZE 1
